### ISSUE TITLE
Strange coverage issues

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt-uglify#39]
As noted on [on this roosevelt-closure PR as well](https://github.com/rooseveltframework/roosevelt-closure/pull/39), this repo is experiencing similar (but slightly different) coverage problems.

On my Mac:

- `npm t`: all tests pass
- `npm run coverage`: this test fails: `should not give a "warning" string since the showWarning param is false`
- `npm run coveralls`: all tests pass but the following error message is thrown: `Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`

Will leave the [0.2.2 PR](https://github.com/rooseveltframework/roosevelt-uglify/pull/38) open until this is resolved.

**Comment by Autre31415** [comment]
#40 should handle all of this
